name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Enter Directory
      run: cd ArenaC
    - name: Run tests
      run: make tests
    - name: run binary
      run: ./bin/tests
    - name: clean up
      run: make clean
