name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: run tests for Arena in C 
      working-direectory: ./ArenaC
      run: 
        make dir 
        make tests
        make cleanup
